/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.GopYDAO;
import Models.GopY;
import java.sql.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haunv
 */
public class Gop_Y_Panel extends javax.swing.JPanel {

    private static Gop_Y_Panel instance;
    private Integer pageIndex = 0;
    private int total;
    private Map<Integer, List<GopY>> listGopY;
    private GopYDAO gopYDAO;
    DefaultTableModel tableModelGopY;

    /**
     * Creates new form Gop_Y_Panel
     */
    public Gop_Y_Panel() {
        initComponents();
        tableModelGopY = (DefaultTableModel) tblDeXuat.getModel();
        listGopY = new HashMap<Integer, List<GopY>>();
        gopYDAO = GopYDAO.getInstance();
        total = gopYDAO.getTotalPage();
        btnInactive.setVisible(false);

        listGopY.put(pageIndex, gopYDAO.selectByPage(Long.valueOf(pageIndex)));
        fillTableGopY(listGopY.get(pageIndex));
    }

    public static Gop_Y_Panel getInstance() {
        if (instance == null) {
            instance = new Gop_Y_Panel();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainContent = new javax.swing.JPanel();
        jScrollPaneDeXuat = new javax.swing.JScrollPane();
        tblDeXuat = new javax.swing.JTable();
        jPanelPage = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnFirst1 = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanelAction = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnIangDeXuat = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        btnInactive = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(10, 10));

        jPanelMainContent.setLayout(new java.awt.BorderLayout(10, 10));

        jScrollPaneDeXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDeXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Nội Dung", "Số Lượt"
            }
        ));
        jScrollPaneDeXuat.setViewportView(tblDeXuat);

        jPanelMainContent.add(jScrollPaneDeXuat, java.awt.BorderLayout.CENTER);

        jPanelPage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 80));
        jPanel4.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel5.setPreferredSize(new java.awt.Dimension(522, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(522, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setPreferredSize(new java.awt.Dimension(50, 97));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setPreferredSize(new java.awt.Dimension(50, 97));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(477, 200));
        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setPreferredSize(new java.awt.Dimension(330, 35));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/First_button.png"))); // NOI18N
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirst1);

        btnPrev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/back_button.png"))); // NOI18N
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrev1);

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/next_button.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext1);

        btnLast1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/Last_button.png"))); // NOI18N
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLast1);

        jPanel2.add(jPanel1, java.awt.BorderLayout.LINE_END);

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setPreferredSize(new java.awt.Dimension(90, 28));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnLamMoi, java.awt.BorderLayout.LINE_START);

        jPanel9.setMinimumSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelPage.add(jPanel4);

        jPanelMainContent.add(jPanelPage, java.awt.BorderLayout.PAGE_END);

        jPanelAction.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 73));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.setPreferredSize(new java.awt.Dimension(78, 30));
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemMoi, new java.awt.GridBagConstraints());

        jPanel12.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12, new java.awt.GridBagConstraints());

        btnIangDeXuat.setText("Tăng Lượt Góp Ý");
        btnIangDeXuat.setPreferredSize(new java.awt.Dimension(123, 30));
        btnIangDeXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIangDeXuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnIangDeXuat, new java.awt.GridBagConstraints());

        jPanel14.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel14, new java.awt.GridBagConstraints());

        btnInactive.setText("Inactive");
        btnInactive.setPreferredSize(new java.awt.Dimension(63, 30));
        btnInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactiveActionPerformed(evt);
            }
        });
        jPanel3.add(btnInactive, new java.awt.GridBagConstraints());

        jPanelAction.add(jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 73));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        txtSearch.setText("Nhập nội dung tìm");
        txtSearch.setPreferredSize(new java.awt.Dimension(149, 30));
        jPanel10.add(txtSearch, new java.awt.GridBagConstraints());

        jPanel11.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new java.awt.GridBagConstraints());

        btnTimKiem.setText("Tìm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(70, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel10.add(btnTimKiem, new java.awt.GridBagConstraints());

        jPanelAction.add(jPanel10);

        jPanelMainContent.add(jPanelAction, java.awt.BorderLayout.PAGE_START);

        add(jPanelMainContent, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GÓP Ý");
        jLabel9.setPreferredSize(new java.awt.Dimension(95, 100));
        add(jLabel9, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
        pageIndex = total;
        List<GopY> list = listGopY.get(pageIndex);
        if (list == null) {
            list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
            listGopY.put(pageIndex, list);
        }
        fillTableGopY(list);
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        if (pageIndex + 1 > total) {
            JOptionPane.showConfirmDialog(this, "Bạn hiện đã ở trang cuối");
        } else {
            pageIndex++;
            List<GopY> list = listGopY.get(pageIndex);
            if (list == null) {
                list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
                listGopY.put(pageIndex, list);
            }
            fillTableGopY(list);
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
        if (pageIndex - 1 < 0) {
            JOptionPane.showConfirmDialog(this, "Bạn hiện đã ở trang đầu");
        } else {
            pageIndex--;
            List<GopY> list = listGopY.get(pageIndex);
            if (list == null) {
                list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
                listGopY.put(pageIndex, list);
            }
            fillTableGopY(list);
        }
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTableGopY(listGopY.get(pageIndex));
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog(this, "Nhập tên đề xuất:", "Thêm đề xuất", JOptionPane.PLAIN_MESSAGE);
        if (s != null) {
            GopY gopY = new GopY();
            gopY.setNoiDung(s);
            gopY.setNgayTao(new Date(Calendar.getInstance().getTimeInMillis()));
            gopY.setTrangThai(Boolean.TRUE);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                pageIndex = 0;
                listGopY.clear();
                listGopY.put(pageIndex, gopYDAO.selectByPage(Long.valueOf(0)));
                fillTableGopY(listGopY.get(pageIndex));
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnIangDeXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIangDeXuatActionPerformed
        // TODO add your handling code here:
        int row = tblDeXuat.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 góp ý");
        } else {
            GopY gopY = listGopY.get(pageIndex).get(row);
            gopY.setSoLuot(gopY.getSoLuot() + 1);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Tăng thành công!");
                listGopY.get(pageIndex).set(row, gopY);
                tableModelGopY.setValueAt(gopY.getSoLuot(), row, 2);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnIangDeXuatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTableGopY(listGopY.get(pageIndex));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập nội dung cần tìm!");
        } else {
            search = "%".concat(search).concat("%");
            List<GopY> list = gopYDAO.selectByKeyword(search);
            if (list.size() != 0) {
                fillTableGopY(list);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            }

        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactiveActionPerformed
        // TODO add your handling code here:
        int row = tblDeXuat.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 góp ý");
        } else {
            GopY gopY = listGopY.get(pageIndex).get(row);
            gopY.setTrangThai(Boolean.FALSE);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Inactive thành công!");
                listGopY.get(pageIndex).set(row, gopY);
                tableModelGopY.setValueAt(gopY.getSoLuot(), row, 2);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnInactiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnIangDeXuat;
    private javax.swing.JButton btnInactive;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelMainContent;
    private javax.swing.JPanel jPanelPage;
    private javax.swing.JScrollPane jScrollPaneDeXuat;
    private javax.swing.JTable tblDeXuat;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void fillTableGopY(List<GopY> list) {
        tableModelGopY.setRowCount(0);
        list.forEach(gopY -> {
            tableModelGopY.addRow(new Object[]{
                gopY.getId(), gopY.getNoiDung(), gopY.getSoLuot()
            });
        });
    }
}
