/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.GopYDAO;
import Models.GopY;
import java.sql.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haunv
 */
public class Gop_Y_Panel extends javax.swing.JPanel {

    private static Gop_Y_Panel instance;
    private Integer pageIndex = 0;
    private int total;
    private Map<Integer, List<GopY>> listGopY;
    private GopYDAO gopYDAO;
    DefaultTableModel tableModelGopY;

    /**
     * Creates new form Gop_Y_Panel
     */
    public Gop_Y_Panel() {
        initComponents();
        tableModelGopY = (DefaultTableModel) tblDeXuat.getModel();
        listGopY = new HashMap<Integer, List<GopY>>();
        gopYDAO = GopYDAO.getInstance();
        total = gopYDAO.getTotalPage();
        btnInactive.setVisible(false);

        listGopY.put(pageIndex, gopYDAO.selectByPage(Long.valueOf(pageIndex)));
        fillTableGopY(listGopY.get(pageIndex));
    }

    public static Gop_Y_Panel getInstance() {
        if (instance == null) {
            instance = new Gop_Y_Panel();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainContent = new javax.swing.JPanel();
        jScrollPaneDeXuat = new javax.swing.JScrollPane();
        tblDeXuat = new javax.swing.JTable();
        jPanelPage = new javax.swing.JPanel();
        btnLast1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();
        btnFirst1 = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanelAction = new javax.swing.JPanel();
        btnIangDeXuat = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnInactive = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanelMainContent.setLayout(new java.awt.BorderLayout());

        tblDeXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Nội Dung", "Số Lượt"
            }
        ));
        jScrollPaneDeXuat.setViewportView(tblDeXuat);

        jPanelMainContent.add(jScrollPaneDeXuat, java.awt.BorderLayout.CENTER);

        btnLast1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/Last_button.png"))); // NOI18N
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/next_button.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnPrev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/back_button.png"))); // NOI18N
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/First_button.png"))); // NOI18N
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPageLayout = new javax.swing.GroupLayout(jPanelPage);
        jPanelPage.setLayout(jPanelPageLayout);
        jPanelPageLayout.setHorizontalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(btnFirst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrev1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast1)
                .addContainerGap())
        );
        jPanelPageLayout.setVerticalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi)
                    .addComponent(btnFirst1)
                    .addComponent(btnPrev1)
                    .addComponent(btnNext1)
                    .addComponent(btnLast1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMainContent.add(jPanelPage, java.awt.BorderLayout.PAGE_END);

        btnIangDeXuat.setText("Tăng Lượt Góp Ý");
        btnIangDeXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIangDeXuatActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        txtSearch.setText("Nhập nội dung tìm");

        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnInactive.setText("Inactive");
        btnInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThemMoi)
                .addGap(10, 10, 10)
                .addComponent(btnIangDeXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInactive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addContainerGap())
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemMoi)
                    .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIangDeXuat)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem)
                        .addComponent(btnInactive)))
                .addContainerGap())
        );

        jPanelMainContent.add(jPanelAction, java.awt.BorderLayout.PAGE_START);

        add(jPanelMainContent, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GÓP Ý");
        jLabel9.setPreferredSize(new java.awt.Dimension(95, 100));
        add(jLabel9, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
        pageIndex = total;
        List<GopY> list = listGopY.get(pageIndex);
        if (list == null) {
            list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
            listGopY.put(pageIndex, list);
        }
        fillTableGopY(list);
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        if (pageIndex + 1 > total) {
            JOptionPane.showConfirmDialog(this, "Bạn hiện đã ở trang cuối");
        } else {
            pageIndex++;
            List<GopY> list = listGopY.get(pageIndex);
            if (list == null) {
                list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
                listGopY.put(pageIndex, list);
            }
            fillTableGopY(list);
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
        if (pageIndex - 1 < 0) {
            JOptionPane.showConfirmDialog(this, "Bạn hiện đã ở trang đầu");
        } else {
            pageIndex--;
            List<GopY> list = listGopY.get(pageIndex);
            if (list == null) {
                list = gopYDAO.selectByPage(Long.valueOf(pageIndex));
                listGopY.put(pageIndex, list);
            }
            fillTableGopY(list);
        }
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTableGopY(listGopY.get(pageIndex));
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog(this, "Nhập tên đề xuất:", "Thêm đề xuất", JOptionPane.PLAIN_MESSAGE);
        if (s != null) {
            GopY gopY = new GopY();
            gopY.setNoiDung(s);
            gopY.setNgayTao(new Date(Calendar.getInstance().getTimeInMillis()));
            gopY.setTrangThai(Boolean.TRUE);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                pageIndex = 0;
                listGopY.clear();
                listGopY.put(pageIndex, gopYDAO.selectByPage(Long.valueOf(0)));
                fillTableGopY(listGopY.get(pageIndex));
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnIangDeXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIangDeXuatActionPerformed
        // TODO add your handling code here:
        int row = tblDeXuat.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 góp ý");
        } else {
            GopY gopY = listGopY.get(pageIndex).get(row);
            gopY.setSoLuot(gopY.getSoLuot() + 1);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Tăng thành công!");
                listGopY.get(pageIndex).set(row, gopY);
                tableModelGopY.setValueAt(gopY.getSoLuot(), row, 2);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnIangDeXuatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTableGopY(listGopY.get(pageIndex));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập nội dung cần tìm!");
        } else {
            search = "%".concat(search).concat("%");
            List<GopY> list = gopYDAO.selectByKeyword(search);
            if (list.size() != 0) {
                fillTableGopY(list);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            }

        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactiveActionPerformed
        // TODO add your handling code here:
        int row = tblDeXuat.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 góp ý");
        } else {
            GopY gopY = listGopY.get(pageIndex).get(row);
            gopY.setTrangThai(Boolean.FALSE);
            if (gopYDAO.insertOnUpdate(gopY) > 0) {
                JOptionPane.showMessageDialog(this, "Inactive thành công!");
                listGopY.get(pageIndex).set(row, gopY);
                tableModelGopY.setValueAt(gopY.getSoLuot(), row, 2);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Server, code: -1");
            }
        }
    }//GEN-LAST:event_btnInactiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnIangDeXuat;
    private javax.swing.JButton btnInactive;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelMainContent;
    private javax.swing.JPanel jPanelPage;
    private javax.swing.JScrollPane jScrollPaneDeXuat;
    private javax.swing.JTable tblDeXuat;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void fillTableGopY(List<GopY> list) {
        tableModelGopY.setRowCount(0);
        list.forEach(gopY -> {
            tableModelGopY.addRow(new Object[]{
                gopY.getId(), gopY.getNoiDung(), gopY.getSoLuot()
            });
        });
    }
}
