/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.HoiVienDao;
import DAO.PhieuMuonChiTietDao;
import DAO.PhieuMuonDao;
import DAO.SachDAO;
import Helper.QrCapture;
import Helper.XImage;
import Models.HoiVien;
import Models.PhieuMuon;
import Models.PhieuMuonChiTiet;
import Models.Sach;
import java.awt.Image;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.sql.Date;
import java.util.Arrays;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hoan
 */
public class QLPhieuMuon_JPanel extends javax.swing.JPanel {

    private Map<Integer, List<PhieuMuon>> listPhieuMuon;
    private Map<Long, PhieuMuonChiTiet> listSachMuon;
    private DefaultTableModel tableModelPhieuMuon;
    private DefaultTableModel tableModelSachMuon;
    private DefaultComboBoxModel boxModelNguoiMuon;
    private PhieuMuonDao phieuMuonDao;
    private HoiVienDao hoiVienDao;
    private SachDAO sachDAO;
    private PhieuMuonChiTietDao phieuMuonChiTietDao;
    private int pageIndex = 0;
    private int totalPage;
    private static QLPhieuMuon_JPanel instance;

    /**
     * Creates new form QLPhieuMuon
     */
    public QLPhieuMuon_JPanel() {
        initComponents();
        phieuMuonDao = PhieuMuonDao.getInstance();
        hoiVienDao = HoiVienDao.getInstance();
        sachDAO = SachDAO.getInstance();
        phieuMuonChiTietDao = PhieuMuonChiTietDao.getInstance();
        listPhieuMuon = new HashMap<Integer, List<PhieuMuon>>();
        listPhieuMuon.put(0, phieuMuonDao.selectByPage(Long.valueOf(pageIndex)));

        listSachMuon = new HashMap<Long, PhieuMuonChiTiet>();

        tableModelPhieuMuon = (DefaultTableModel) tblPhieuMuon.getModel();
        tableModelSachMuon = (DefaultTableModel) tblSachMuon.getModel();
        boxModelNguoiMuon = (DefaultComboBoxModel) jComboBoxNguoiMuon.getModel();

        fillTablePhieuMuon(listPhieuMuon.get(0));
        fillComBoBoxNguoiMuon();

        jTabbedPane1.remove(jPanelCapNhat);
        totalPage = phieuMuonDao.getTotalPage();
    }

    public static QLPhieuMuon_JPanel getInstance() {
        if (instance == null) {
            instance = new QLPhieuMuon_JPanel();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDanhSach = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonTimKiemPhieuMuon = new javax.swing.JButton();
        txtTimKiemPhieuMuon = new javax.swing.JTextField();
        btnThemPhieuMuon = new javax.swing.JButton();
        jButtonChiTietPhieuMuon = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();
        jPanelPhanTrang = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jPanelCapNhat = new javax.swing.JPanel();
        jPanelWrapCapNhat = new javax.swing.JPanel();
        jPanelDetailSach = new javax.swing.JPanel();
        jLabelNgayTra = new javax.swing.JLabel();
        jLabelMaPhieuMuon = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        jLabelNguoiMuon = new javax.swing.JLabel();
        jLabelNgayMuon = new javax.swing.JLabel();
        btnDownLoadQR = new javax.swing.JButton();
        jLabelErrorMaPhieuMuon = new javax.swing.JLabel();
        jLabelErrorNgayMuon = new javax.swing.JLabel();
        jDateChooserNgayMuon = new com.toedter.calendar.JDateChooser();
        jLabelErrorNguoiMuon = new javax.swing.JLabel();
        jComboBoxNguoiMuon = new javax.swing.JComboBox<>();
        jLabelErrorNgayTra = new javax.swing.JLabel();
        jDateChooserNgayMuon1 = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayTra = new com.toedter.calendar.JDateChooser();
        lblQR_CODE = new javax.swing.JLabel();
        jPanelSachMuon = new javax.swing.JPanel();
        jLabelSachMuon = new javax.swing.JLabel();
        btnScanSach = new javax.swing.JButton();
        jButtonThemSachMuon = new javax.swing.JButton();
        jLabelErrorAction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachMuon = new javax.swing.JTable();
        btnMark = new javax.swing.JButton();
        jPanelAction = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanelDanhSach.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel3.setPreferredSize(new java.awt.Dimension(648, 50));

        jButtonTimKiemPhieuMuon.setText("Tìm kiếm");
        jButtonTimKiemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemPhieuMuonActionPerformed(evt);
            }
        });

        btnThemPhieuMuon.setText("Thêm Mới");
        btnThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuMuonActionPerformed(evt);
            }
        });

        jButtonChiTietPhieuMuon.setText("Chi Tiết");
        jButtonChiTietPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiTietPhieuMuonActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChiTietPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 611, Short.MAX_VALUE)
                .addComponent(txtTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemPhieuMuon)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChiTietPhieuMuon)
                    .addComponent(btnThemPhieuMuon)
                    .addComponent(btnLamMoi))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelDanhSach.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setColumnHeaderView(null);

        tblPhieuMuon.setAutoCreateRowSorter(true);
        tblPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu", "Ngày mượn", "Thời hạn trả", "Người xử lí", "QR_CODE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuMuon.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhieuMuon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPhieuMuon.setRowHeight(25);
        tblPhieuMuon.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane.setViewportView(tblPhieuMuon);

        jPanelDanhSach.add(jScrollPane, java.awt.BorderLayout.CENTER);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/Last_button.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/next_button.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/back_button.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/First_button.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPhanTrangLayout = new javax.swing.GroupLayout(jPanelPhanTrang);
        jPanelPhanTrang.setLayout(jPanelPhanTrangLayout);
        jPanelPhanTrangLayout.setHorizontalGroup(
            jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanTrangLayout.createSequentialGroup()
                .addContainerGap(849, Short.MAX_VALUE)
                .addComponent(btnFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast)
                .addContainerGap())
        );
        jPanelPhanTrangLayout.setVerticalGroup(
            jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanelDanhSach.add(jPanelPhanTrang, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Danh Sách", jPanelDanhSach);

        jPanelCapNhat.setLayout(new java.awt.BorderLayout());

        jPanelWrapCapNhat.setLayout(new java.awt.BorderLayout());

        jPanelDetailSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNgayTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayTra.setText("Ngày trả:");
        jPanelDetailSach.add(jLabelNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabelMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaPhieuMuon.setText("Mã phiếu mượn:");
        jPanelDetailSach.add(jLabelMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaPhieuMuon.setEnabled(false);
        jPanelDetailSach.add(txtMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 420, -1));

        jLabelNguoiMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNguoiMuon.setText("Người mượn:");
        jPanelDetailSach.add(jLabelNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelNgayMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayMuon.setText("Ngày mượn:");
        jPanelDetailSach.add(jLabelNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnDownLoadQR.setText("Print");
        btnDownLoadQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownLoadQRActionPerformed(evt);
            }
        });
        jPanelDetailSach.add(btnDownLoadQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 120, 30));

        jLabelErrorMaPhieuMuon.setText(" ");
        jPanelDetailSach.add(jLabelErrorMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 420, 10));
        jPanelDetailSach.add(jLabelErrorNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 420, 10));

        jDateChooserNgayMuon.setDateFormatString("dd-MM-yyyy");
        jDateChooserNgayMuon.setEnabled(false);
        jPanelDetailSach.add(jDateChooserNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 420, 23));
        jPanelDetailSach.add(jLabelErrorNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 420, 10));

        jComboBoxNguoiMuon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelDetailSach.add(jComboBoxNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 420, -1));
        jPanelDetailSach.add(jLabelErrorNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 420, 10));
        jPanelDetailSach.add(jDateChooserNgayMuon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 420, -1));
        jPanelDetailSach.add(jDateChooserNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 420, -1));
        jPanelDetailSach.add(lblQR_CODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 190, 190));

        jPanelWrapCapNhat.add(jPanelDetailSach, java.awt.BorderLayout.PAGE_START);

        jLabelSachMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSachMuon.setText("Danh Sách:");

        btnScanSach.setText("Scan");
        btnScanSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanSachActionPerformed(evt);
            }
        });

        jButtonThemSachMuon.setText("Thêm Sách");
        jButtonThemSachMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSachMuonActionPerformed(evt);
            }
        });

        jLabelErrorAction.setText(" ");

        tblSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Ngày trả", "Người Xử Lý", "Đã trả sách?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSachMuon);
        if (tblSachMuon.getColumnModel().getColumnCount() > 0) {
            tblSachMuon.getColumnModel().getColumn(2).setResizable(false);
            tblSachMuon.getColumnModel().getColumn(3).setResizable(false);
            tblSachMuon.getColumnModel().getColumn(4).setResizable(false);
            tblSachMuon.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        btnMark.setText("Đánh dấu trả sách");
        btnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSachMuonLayout = new javax.swing.GroupLayout(jPanelSachMuon);
        jPanelSachMuon.setLayout(jPanelSachMuonLayout);
        jPanelSachMuonLayout.setHorizontalGroup(
            jPanelSachMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSachMuonLayout.createSequentialGroup()
                .addGroup(jPanelSachMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSachMuonLayout.createSequentialGroup()
                        .addComponent(jLabelErrorAction, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnScanSach, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonThemSachMuon))
                    .addGroup(jPanelSachMuonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSachMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSachMuonLayout.createSequentialGroup()
                                .addComponent(jLabelSachMuon)
                                .addGap(0, 1013, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanelSachMuonLayout.setVerticalGroup(
            jPanelSachMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSachMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSachMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSachMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemSachMuon)
                    .addComponent(btnScanSach)
                    .addComponent(jLabelErrorAction)
                    .addComponent(btnMark))
                .addContainerGap())
        );

        jPanelWrapCapNhat.add(jPanelSachMuon, java.awt.BorderLayout.CENTER);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/cleaning.png"))); // NOI18N
        btnClear.setText("Làm Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/add.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnXoaSach.setText("Xóa Sách");
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionLayout = new javax.swing.GroupLayout(jPanelAction);
        jPanelAction.setLayout(jPanelActionLayout);
        jPanelActionLayout.setHorizontalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jPanelActionLayout.setVerticalGroup(
            jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelWrapCapNhat.add(jPanelAction, java.awt.BorderLayout.PAGE_END);

        jPanelCapNhat.add(jPanelWrapCapNhat, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Cập Nhật", jPanelCapNhat);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QUẢN LÝ PHIẾU MƯỢN");
        jLabel9.setPreferredSize(new java.awt.Dimension(95, 100));
        add(jLabel9, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PhieuMuon phieuMuon = getForm();
        if (phieuMuon == null) {
            return;
        } else {
            List<PhieuMuonChiTiet> phieuMuonChiTiets = new ArrayList<PhieuMuonChiTiet>();
            listSachMuon.forEach((key, pmct) -> phieuMuonChiTiets.add(pmct));
            phieuMuon.setListPhieuMuonChiTiets(phieuMuonChiTiets);

            if (phieuMuon.getId() == null) {
                Long id = Long.valueOf(phieuMuonDao.insertOnUpdate(phieuMuon));
                if (id <= 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại!");
                    return;
                } else {
                    System.out.println("id->" + id);
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    phieuMuon.setId(id);
                    txtMaPhieuMuon.setText(id.toString());
                    pageIndex = 0;
                    listPhieuMuon.clear();
                    listPhieuMuon.put(0, phieuMuonDao.selectByPage(Long.valueOf(pageIndex)));
                    
                    String qr_codeKey = phieuMuon.getQr_code(); // create key phieuMuon
                    String qr_codePath = Helper.XImage.PHIEUMUON_UPLOAD + "/" + phieuMuon.getQr_code().toString().split("-")[1] + ".png"; //create qr_code path
                    // create qr_code image and parse qrcode image fit with label qr_code
                    if (Helper.QR_CODE.generateQRcode(qr_codeKey, qr_codePath)) {
                        try {
                            lblQR_CODE.setIcon(new ImageIcon(new ImageIcon(qr_codePath).getImage().getScaledInstance(190, 190, Image.SCALE_DEFAULT)));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }

            } else {
                if (phieuMuonDao.insertOnUpdate(phieuMuon) <= 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                    phieuMuon = phieuMuonDao.selectByID(phieuMuon.getId());
                    List<PhieuMuon> list = listPhieuMuon.get(pageIndex);
                    for (int i = 0; i < list.size(); ++i) {
                        if (list.get(i).getId().equals(phieuMuon.getId())) {
                            list.set(i, phieuMuon);
                            break;
                        }
                    }
                }

            }
            //save phieu muon
            // save sach
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        resetForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        pageIndex = totalPage;
        fillTablePhieuMuon(listPhieuMuon.get(pageIndex));
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (pageIndex + 1 > totalPage) {
            JOptionPane.showMessageDialog(this, "Hiện đã là trang đầu tiên!");
            return;
        } else {
            pageIndex++;
            List<PhieuMuon> listPM = listPhieuMuon.get(pageIndex);
            if (listPM == null) {
                listPM = phieuMuonDao.selectByPage(Long.valueOf(pageIndex));
            }
            fillTablePhieuMuon(listPM);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:

        if (pageIndex - 1 < 0) {
            JOptionPane.showMessageDialog(this, "Hiện đã là trang đầu tiên!");
            return;
        } else {
            pageIndex--;
            fillTablePhieuMuon(listPhieuMuon.get(pageIndex));
        }

    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTablePhieuMuon(listPhieuMuon.get(pageIndex));
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        btnSave.setText("Thêm");
        resetForm();
        activeTabCapNhat();
    }//GEN-LAST:event_btnThemPhieuMuonActionPerformed

    private void jButtonChiTietPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiTietPhieuMuonActionPerformed
        // TODO add your handling code here:
        int row = tblPhieuMuon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn phiếu mượn cần xem!");
        } else {
            listSachMuon.clear();
            btnSave.setText("Lưu");
            PhieuMuon phieuM = listPhieuMuon.get(pageIndex).get(row);
            setForm(phieuM);
            activeTabCapNhat();
        }
    }//GEN-LAST:event_jButtonChiTietPhieuMuonActionPerformed

    private void btnScanSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanSachActionPerformed
        // TODO add your handling code here:
        final Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                Helper.QrCapture.getInsance("PHIEU_MUON").show();
            }
        });
        thread.start();

    }//GEN-LAST:event_btnScanSachActionPerformed

    private void jButtonTimKiemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemPhieuMuonActionPerformed
        // TODO add your handling code here:
        String search = txtTimKiemPhieuMuon.getText();
        List<PhieuMuon> list;
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập thông tin cần tìm kiếm!");
        } else {
            search = "%" + search + "%";
            list = phieuMuonDao.selectALLByKey(search);
            fillTablePhieuMuon(list);
        }
    }//GEN-LAST:event_jButtonTimKiemPhieuMuonActionPerformed

    private void jButtonThemSachMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSachMuonActionPerformed
        // TODO add your handling code here:
        Chon_Sach_JDialog.getInstance().show("PHIEU_MUON");
    }//GEN-LAST:event_jButtonThemSachMuonActionPerformed

    private void btnDownLoadQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownLoadQRActionPerformed
        // TODO add your handling code here:
        if (lblQR_CODE.getIcon() == null)
            System.out.println("null");
    }//GEN-LAST:event_btnDownLoadQRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        pageIndex = 0;
        fillTablePhieuMuon(listPhieuMuon.get(pageIndex));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        // TODO add your handling code here:
        int row = tblSachMuon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sách cần xóa!");
        } else {
            long maSach = Long.valueOf(tblSachMuon.getValueAt(row, 0).toString());
            listSachMuon.remove(maSach);
            tableModelSachMuon.removeRow(row);
        }
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkActionPerformed
        // TODO add your handling code here:
        int row = tblSachMuon.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sách cần đánh dấu!");
        } else {
            PhieuMuonChiTiet pmct = listSachMuon.get(Long.valueOf(tblSachMuon.getValueAt(row, 0).toString()));
            pmct.setNguoiXuLy(Helper.Auth.user.getMaQL());
            pmct.setNgayTra(new Date(Calendar.getInstance().getTimeInMillis()));
            pmct.setTrangThai(true);
            if (phieuMuonChiTietDao.insertOnUpdate(pmct) <= 0) {
                JOptionPane.showMessageDialog(this, "Đánh Dấu trả sách thất bại!");
            } else {
                tblSachMuon.setValueAt(pmct.getNgayTra(), row, 2);
                tblSachMuon.setValueAt(pmct.getNguoiXuLy(), row, 3);
                tblSachMuon.setValueAt("Đã trả", row, 4);
                JOptionPane.showMessageDialog(this, "Đánh Dấu trả sách thành công!");
            }
        }
    }//GEN-LAST:event_btnMarkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDownLoadQR;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMark;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnScanSach;
    private javax.swing.JButton btnThemPhieuMuon;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonChiTietPhieuMuon;
    private javax.swing.JButton jButtonThemSachMuon;
    private javax.swing.JButton jButtonTimKiemPhieuMuon;
    private javax.swing.JComboBox<String> jComboBoxNguoiMuon;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMuon;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMuon1;
    private com.toedter.calendar.JDateChooser jDateChooserNgayTra;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorAction;
    private javax.swing.JLabel jLabelErrorMaPhieuMuon;
    private javax.swing.JLabel jLabelErrorNgayMuon;
    private javax.swing.JLabel jLabelErrorNgayTra;
    private javax.swing.JLabel jLabelErrorNguoiMuon;
    private javax.swing.JLabel jLabelMaPhieuMuon;
    private javax.swing.JLabel jLabelNgayMuon;
    private javax.swing.JLabel jLabelNgayTra;
    private javax.swing.JLabel jLabelNguoiMuon;
    private javax.swing.JLabel jLabelSachMuon;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelCapNhat;
    private javax.swing.JPanel jPanelDanhSach;
    private javax.swing.JPanel jPanelDetailSach;
    private javax.swing.JPanel jPanelPhanTrang;
    private javax.swing.JPanel jPanelSachMuon;
    private javax.swing.JPanel jPanelWrapCapNhat;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQR_CODE;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTable tblSachMuon;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtTimKiemPhieuMuon;
    // End of variables declaration//GEN-END:variables

    public void activeTabCapNhat() {
        jTabbedPane1.add(jPanelCapNhat, "Cập Nhật");
        jTabbedPane1.setSelectedIndex(1);
    }

    public void fillTablePhieuMuon(List<PhieuMuon> list) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        tableModelPhieuMuon.setRowCount(0);
        if (list == null) {
            JOptionPane.showMessageDialog(this, "Không có sách nào!");
            return;
        }
        for (int i = 0; i < list.size(); ++i) {
            PhieuMuon phieuMuon = list.get(i);
            tableModelPhieuMuon.addRow(new Object[]{
                i + 1, phieuMuon.getId(), dateFormat.format(phieuMuon.getNgayMuon()), dateFormat.format(phieuMuon.getHanTra()), phieuMuon.getNguoiXuLy(), phieuMuon.getQr_code()
            });
        }
    }

    public void fillComBoBoxNguoiMuon() {
        List<HoiVien> listNguoiMuon = hoiVienDao.selectALL();
        if (listNguoiMuon == null) {
            return;
        }
        boxModelNguoiMuon.removeAllElements();
        listNguoiMuon.forEach((nguoiMuon) -> boxModelNguoiMuon.addElement(nguoiMuon.getId() + "-" + nguoiMuon.getFullName()));
    }

    public PhieuMuon getForm() {
        Long maPhieuMuon = txtMaPhieuMuon.getText().isEmpty() ? null : Long.valueOf(txtMaPhieuMuon.getText()); //parse maPhieuMuon
        String nguoiMuon = jComboBoxNguoiMuon.getSelectedItem().toString().split("-")[0]; // parse id hoiVien
        Date ngayMuon = new Date(jDateChooserNgayMuon.getDate().getTime()); // parse date
        Date ngayTra = jDateChooserNgayTra.getDate() == null ? null : new Date(jDateChooserNgayTra.getDate().getTime());

        int check = 0;
        //check valid date
        //check valid date
        if (ngayTra == null) {
            jLabelErrorNgayTra.setText("Định dạng ngày tháng phải là 05-03-2021");
        } else if (ngayTra.before(ngayMuon)) {
            jLabelErrorNgayTra.setText("Ngày trả phải sau ngày mượn!");
        } else {
            check++;
            jLabelErrorNgayTra.setText("");
        }
        //check list sachMuon exist?
        if (listSachMuon.size() == 0) {
            jLabelErrorAction.setText("Hãy chọn sách cần mượn!");
        } else {
            check++;
        }

        PhieuMuon phieuMuon = null;
        if (check == 2) {
            phieuMuon = new PhieuMuon();
            phieuMuon.setId(maPhieuMuon);
            phieuMuon.setNguoiXuLy(Helper.Auth.user.getMaQL());
            phieuMuon.setNguoiMuon(Long.valueOf(nguoiMuon));
            phieuMuon.setNgayMuon(ngayMuon);
            phieuMuon.setHanTra(ngayTra);

            if (maPhieuMuon == null) {
                Long timeNow = Calendar.getInstance().getTimeInMillis();
                phieuMuon.setQr_code("sach-" + timeNow);
            } else {
                int row = tblPhieuMuon.getSelectedRow();
                phieuMuon.setQr_code(listPhieuMuon.get(pageIndex).get(row).getQr_code());
            }
        }

        return phieuMuon;
    }

    public void setForm(PhieuMuon phieuMuon) {
        txtMaPhieuMuon.setText(String.valueOf(phieuMuon.getId()));
        jDateChooserNgayMuon.setDate(phieuMuon.getNgayMuon());
        jDateChooserNgayTra.setDate(phieuMuon.getHanTra());
        btnDownLoadQR.setVisible(true);
        tableModelSachMuon.setRowCount(0);

        new Thread() {
            @Override
            public void run() {
                HoiVien nguoiMuon = hoiVienDao.selectByID(phieuMuon.getNguoiMuon());
                jComboBoxNguoiMuon.setSelectedItem(nguoiMuon.getId() + "-" + nguoiMuon.getFullName());
            }

        }.start();

        new Thread() {
            @Override
            public void run() {
                phieuMuon.setListPhieuMuonChiTiets(phieuMuonChiTietDao.selectALL(phieuMuon.getId()));
                if (phieuMuon.getListPhieuMuonChiTiets() != null) {
                    phieuMuon.getListPhieuMuonChiTiets().forEach((pmct) -> {
                        new Thread() {
                            @Override
                            public void run() {
                                Sach sach = sachDAO.selectByID(pmct.getSach());
                                listSachMuon.put(sach.getId(), pmct);
                                tableModelSachMuon.addRow(new Object[]{
                                    sach.getId(),
                                    sach.getTenSach(),
                                    pmct.getNgayTra() == null ? "" : pmct.getNgayTra(),
                                    pmct.getNguoiXuLy(),
                                    pmct.isTrangThai() ? "Đã trả sách" : "Chưa trả sách"
                                });
                            }

                        }.start();

                    }
                    );
                }
            }
        }.start();

        if (phieuMuon.getQr_code()
                != null) {
            System.out.println("qr_code phieuMuon->" + phieuMuon.getQr_code());
            try {
                lblQR_CODE.setIcon(new ImageIcon(
                        new ImageIcon(Helper.XImage.PHIEUMUON_UPLOAD.concat("/" + phieuMuon.getQr_code().split("-")[1] + ".png"))
                                .getImage()
                                .getScaledInstance(190, 190, Image.SCALE_DEFAULT)));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void resetForm() {
        listSachMuon.clear();
        txtMaPhieuMuon.setText(null);
        jComboBoxNguoiMuon.setSelectedIndex(0);
        jDateChooserNgayMuon.setDate(Calendar.getInstance().getTime());
        jDateChooserNgayTra.setDate(null);
        tableModelSachMuon.setRowCount(0);
        lblQR_CODE.setIcon(null);
        btnDownLoadQR.setVisible(false);
    }

    public boolean addSachMuon(PhieuMuonChiTiet pmct, Sach sach) {
        if (listSachMuon.containsKey(sach.getId())) {
            return false;
        } else {
            listSachMuon.put(sach.getId(), pmct);
            tableModelSachMuon.addRow(new Object[]{
                sach.getId().toString(), sach.getTenSach(),
                null,
                pmct.getNguoiXuLy(),
                "Mới"
            });
            return true;
        }
    }

    public String addSachFromSacanner(String key) {
        Sach sach = null; //use key find sach

        if (sach != null) {
            tableModelSachMuon.addRow(new Object[]{sach.getId(), sach.getTenSach(), sach.getNhaXuatBan()});
            return sach.getTenSach();
        }
        return null;
    }
}
