/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Helper.QrCapture;
import Helper.XImage;
import Models.HoiVien;
import Models.PhieuMuon;
import Models.Sach;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.sql.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hoan
 */
public class QLPhieuMuon_JPanel extends javax.swing.JPanel {

    private List<PhieuMuon> listPhieuMuon;
    private DefaultTableModel tableModelPhieuMuon;
    private DefaultTableModel tableModelSachMuon;
    private DefaultComboBoxModel boxModelNguoiMuon;
    private Map<Long, Sach> ListSachMuon;
    private static QLPhieuMuon_JPanel instance;

    /**
     * Creates new form QLPhieuMuon
     */
    public QLPhieuMuon_JPanel() {
        initComponents();
        jTabbedPane1.remove(jPanelCapNhat);
        listPhieuMuon = new ArrayList<PhieuMuon>();
        ListSachMuon = new HashMap<Long, Sach>();
        tableModelPhieuMuon = (DefaultTableModel) tblPhieuMuon.getModel();
        tableModelSachMuon = (DefaultTableModel) tblSachMuon.getModel();
        boxModelNguoiMuon = (DefaultComboBoxModel) jComboBoxNguoiMuon.getModel();

        fillTablePhieuMuon();
        fillComBoBoxNguoiMuon();
    }

    public static QLPhieuMuon_JPanel getInstance() {
        if (instance == null) {
            instance = new QLPhieuMuon_JPanel();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDanhSach = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonTimKiemPhieuMuon = new javax.swing.JButton();
        txtTimKiemPhieuMuon = new javax.swing.JTextField();
        jButtonThemPhieuMuon = new javax.swing.JButton();
        jButtonChiTietPhieuMuon = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();
        jPanelPhanTrang = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jPanelCapNhat = new javax.swing.JPanel();
        jPanelWrapCapNhat = new javax.swing.JPanel();
        jLabelNgayTra = new javax.swing.JLabel();
        jLabelMaPhieuMuon = new javax.swing.JLabel();
        jLabelSachMuon = new javax.swing.JLabel();
        jTextFieldMaPhieuMuon = new javax.swing.JTextField();
        jLabelNguoiMuon = new javax.swing.JLabel();
        jLabelNgayMuon = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanelQR_CODE = new javax.swing.JPanel();
        jLabelQR_CODE = new javax.swing.JLabel();
        jButtonDownLoadQR = new javax.swing.JButton();
        jScrollPaneSachMuon = new javax.swing.JScrollPane();
        tblSachMuon = new javax.swing.JTable();
        btnScanSach = new javax.swing.JButton();
        jDateChooserNgayTra = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayMuon = new com.toedter.calendar.JDateChooser();
        jLabelErrorMaPhieuMuon = new javax.swing.JLabel();
        jLabelErrorAction = new javax.swing.JLabel();
        jComboBoxNguoiMuon = new javax.swing.JComboBox<>();
        jLabelErrorNguoiMuon = new javax.swing.JLabel();
        jLabelErrorNgayMuon = new javax.swing.JLabel();
        jLabelErrorNgayTra = new javax.swing.JLabel();
        jButtonThemSach1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanelDanhSach.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel3.setPreferredSize(new java.awt.Dimension(648, 50));

        jButtonTimKiemPhieuMuon.setText("Tìm kiếm");
        jButtonTimKiemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemPhieuMuonActionPerformed(evt);
            }
        });

        jButtonThemPhieuMuon.setText("Thêm Mới");
        jButtonThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemPhieuMuonActionPerformed(evt);
            }
        });

        jButtonChiTietPhieuMuon.setText("Chi Tiết");
        jButtonChiTietPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiTietPhieuMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonThemPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChiTietPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(txtTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiemPhieuMuon)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChiTietPhieuMuon)
                    .addComponent(jButtonThemPhieuMuon))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelDanhSach.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setColumnHeaderView(null);

        tblPhieuMuon.setAutoCreateRowSorter(true);
        tblPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu", "Người Mượn", "Ngày mượn", "Thời hạn trả", "Người xử lí", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuMuon.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhieuMuon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPhieuMuon.setRowHeight(25);
        tblPhieuMuon.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane.setViewportView(tblPhieuMuon);

        jPanelDanhSach.add(jScrollPane, java.awt.BorderLayout.CENTER);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/Last_button.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/next_button.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/back_button.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/First_button.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPhanTrangLayout = new javax.swing.GroupLayout(jPanelPhanTrang);
        jPanelPhanTrang.setLayout(jPanelPhanTrangLayout);
        jPanelPhanTrangLayout.setHorizontalGroup(
            jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanTrangLayout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(btnFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast)
                .addContainerGap())
        );
        jPanelPhanTrangLayout.setVerticalGroup(
            jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanelDanhSach.add(jPanelPhanTrang, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Danh Sách", jPanelDanhSach);

        jPanelCapNhat.setLayout(new java.awt.BorderLayout());

        jPanelWrapCapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNgayTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayTra.setText("Ngày trả:");
        jPanelWrapCapNhat.add(jLabelNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabelMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaPhieuMuon.setText("Mã phiếu mượn:");
        jPanelWrapCapNhat.add(jLabelMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelSachMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSachMuon.setText("Danh Sách:");
        jPanelWrapCapNhat.add(jLabelSachMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jTextFieldMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMaPhieuMuon.setEnabled(false);
        jPanelWrapCapNhat.add(jTextFieldMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 240, -1));

        jLabelNguoiMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNguoiMuon.setText("Người mượn:");
        jPanelWrapCapNhat.add(jLabelNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabelNgayMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNgayMuon.setText("Ngày mượn:");
        jPanelWrapCapNhat.add(jLabelNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/add.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanelWrapCapNhat.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 62, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Icon/cleaning.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanelWrapCapNhat.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 62, -1));

        javax.swing.GroupLayout jPanelQR_CODELayout = new javax.swing.GroupLayout(jPanelQR_CODE);
        jPanelQR_CODE.setLayout(jPanelQR_CODELayout);
        jPanelQR_CODELayout.setHorizontalGroup(
            jPanelQR_CODELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQR_CODELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQR_CODE, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelQR_CODELayout.setVerticalGroup(
            jPanelQR_CODELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQR_CODELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQR_CODE, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelWrapCapNhat.add(jPanelQR_CODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 47, -1, -1));

        jButtonDownLoadQR.setText("Download");
        jButtonDownLoadQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownLoadQRActionPerformed(evt);
            }
        });
        jPanelWrapCapNhat.add(jButtonDownLoadQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 191, 30));

        tblSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Nhà Xuất Bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneSachMuon.setViewportView(tblSachMuon);

        jPanelWrapCapNhat.add(jScrollPaneSachMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 630, 140));

        btnScanSach.setText("Scan");
        btnScanSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanSachActionPerformed(evt);
            }
        });
        jPanelWrapCapNhat.add(btnScanSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        jDateChooserNgayTra.setDateFormatString("dd-MM-yyyy");
        jPanelWrapCapNhat.add(jDateChooserNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, 23));

        jDateChooserNgayMuon.setDateFormatString("dd-MM-yyyy");
        jPanelWrapCapNhat.add(jDateChooserNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 240, 23));

        jLabelErrorMaPhieuMuon.setText(" ");
        jPanelWrapCapNhat.add(jLabelErrorMaPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, -1));

        jLabelErrorAction.setText(" ");
        jPanelWrapCapNhat.add(jLabelErrorAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 370, -1));

        jComboBoxNguoiMuon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelWrapCapNhat.add(jComboBoxNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, -1));
        jPanelWrapCapNhat.add(jLabelErrorNguoiMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, 10));
        jPanelWrapCapNhat.add(jLabelErrorNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 10));
        jPanelWrapCapNhat.add(jLabelErrorNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, 10));

        jButtonThemSach1.setText("Thêm Sách");
        jButtonThemSach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSach1ActionPerformed(evt);
            }
        });
        jPanelWrapCapNhat.add(jButtonThemSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        jPanelCapNhat.add(jPanelWrapCapNhat, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Cập Nhật", jPanelCapNhat);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QUẢN LÝ PHIẾU MƯỢN");
        jLabel9.setPreferredSize(new java.awt.Dimension(95, 100));
        add(jLabel9, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PhieuMuon phieuMuon = getForm();
        if (phieuMuon == null) {
            return;
        } else if (ListSachMuon.size() == 0) {
            jLabelErrorAction.setText("Hãy chọn sách cần mượn!");
        } else {
            //save phieu muon
            // save sach
            String qr_codeKey = phieuMuon.getQr_code().split("-")[1];
            String qr_codePath = Helper.XImage.PHIEUMUON_UPLOAD + "/" + qr_codeKey + ".png";
            if (Helper.QR_CODE.generateQRcode(qr_codeKey, qr_codePath)) {
                jLabelQR_CODE.setIcon(new ImageIcon(new ImageIcon(qr_codePath).getImage().getScaledInstance(jLabelQR_CODE.getWidth(), jLabelQR_CODE.getWidth(), HEIGHT)));
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        listPhieuMuon = null;
        fillTablePhieuMuon();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        listPhieuMuon = null;
        if (listPhieuMuon == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sách!");
        }
        fillTablePhieuMuon();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        listPhieuMuon = null;
        if (listPhieuMuon == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sách!");
        }
        fillTablePhieuMuon();
        fillComBoBoxNguoiMuon();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        listPhieuMuon = null;
        fillTablePhieuMuon();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void jButtonThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemPhieuMuonActionPerformed
        // TODO add your handling code here:
        activeTabCapNhat();
    }//GEN-LAST:event_jButtonThemPhieuMuonActionPerformed

    private void jButtonChiTietPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiTietPhieuMuonActionPerformed
        // TODO add your handling code here:
        activeTabCapNhat();
    }//GEN-LAST:event_jButtonChiTietPhieuMuonActionPerformed

    private void btnScanSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanSachActionPerformed
        // TODO add your handling code here:
        final Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                Helper.QrCapture.getInsance("PHIEU_MUON").show();
            }
        });
        thread.start();

    }//GEN-LAST:event_btnScanSachActionPerformed

    private void jButtonTimKiemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemPhieuMuonActionPerformed
        // TODO add your handling code here:
        String search = txtTimKiemPhieuMuon.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập thông tin cần tìm kiếm!");
        } else {
            listPhieuMuon = null;
            fillTablePhieuMuon();
        }
    }//GEN-LAST:event_jButtonTimKiemPhieuMuonActionPerformed

    private void jButtonThemSach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSach1ActionPerformed
        // TODO add your handling code here:
        Chon_Sach_JDialog.getInstance().show("PHIEU_MUON");
    }//GEN-LAST:event_jButtonThemSach1ActionPerformed

    private void jButtonDownLoadQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownLoadQRActionPerformed
        // TODO add your handling code here:
        if(jLabelQR_CODE.getIcon() == null)
            System.out.println("null");
    }//GEN-LAST:event_jButtonDownLoadQRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnScanSach;
    private javax.swing.JButton jButtonChiTietPhieuMuon;
    private javax.swing.JButton jButtonDownLoadQR;
    private javax.swing.JButton jButtonThemPhieuMuon;
    private javax.swing.JButton jButtonThemSach1;
    private javax.swing.JButton jButtonTimKiemPhieuMuon;
    private javax.swing.JComboBox<String> jComboBoxNguoiMuon;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMuon;
    private com.toedter.calendar.JDateChooser jDateChooserNgayTra;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorAction;
    private javax.swing.JLabel jLabelErrorMaPhieuMuon;
    private javax.swing.JLabel jLabelErrorNgayMuon;
    private javax.swing.JLabel jLabelErrorNgayTra;
    private javax.swing.JLabel jLabelErrorNguoiMuon;
    private javax.swing.JLabel jLabelMaPhieuMuon;
    private javax.swing.JLabel jLabelNgayMuon;
    private javax.swing.JLabel jLabelNgayTra;
    private javax.swing.JLabel jLabelNguoiMuon;
    private javax.swing.JLabel jLabelQR_CODE;
    private javax.swing.JLabel jLabelSachMuon;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCapNhat;
    private javax.swing.JPanel jPanelDanhSach;
    private javax.swing.JPanel jPanelPhanTrang;
    private javax.swing.JPanel jPanelQR_CODE;
    private javax.swing.JPanel jPanelWrapCapNhat;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPaneSachMuon;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldMaPhieuMuon;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTable tblSachMuon;
    private javax.swing.JTextField txtTimKiemPhieuMuon;
    // End of variables declaration//GEN-END:variables

    public void activeTabCapNhat() {
        jTabbedPane1.add(jPanelCapNhat, "Cập Nhật");
        jTabbedPane1.setSelectedIndex(1);
    }

    public void fillTablePhieuMuon() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));
        listPhieuMuon.add(new PhieuMuon(1l, "smm", "12", new Date(2021, 11, 24), new Date(2021, 11, 24), "qrcode"));

        tableModelPhieuMuon.setRowCount(0);

        for (int i = 0; i < listPhieuMuon.size(); ++i) {
            PhieuMuon phieuMuon = listPhieuMuon.get(i);
            tableModelPhieuMuon.addRow(new Object[]{
                i + 1, phieuMuon.getId(), phieuMuon.getNguoiMuon(), dateFormat.format(phieuMuon.getNgayMuon()), dateFormat.format(phieuMuon.getHanTra()), phieuMuon.getNguoiXuLy(), phieuMuon.getQr_code()
            });

        }
    }

    public void fillComBoBoxNguoiMuon() {
        List<String> listNguoiMuon = new ArrayList<String>();
        listNguoiMuon.add("1-SHIKI");
        listNguoiMuon.add("2-HAU");
        listNguoiMuon.add("3-ORIS");

        boxModelNguoiMuon.removeAllElements();
        listNguoiMuon.forEach((nguoiMuon) -> boxModelNguoiMuon.addElement(nguoiMuon));
    }

    public PhieuMuon getForm() {
        Long maPhieuMuon = jTextFieldMaPhieuMuon.getText().isEmpty() ? null : Long.valueOf(jTextFieldMaPhieuMuon.getText());
        String nguoiMuon = jComboBoxNguoiMuon.getSelectedItem().toString().split("-")[0];
        Date ngayMuon = jDateChooserNgayMuon.getDate() == null ? null : new Date(jDateChooserNgayMuon.getDate().getTime());
        Date ngayTra = jDateChooserNgayTra.getDate() == null ? null : new Date(jDateChooserNgayTra.getDate().getTime());

        int check = 0;
        if (ngayMuon == null) {
            jLabelErrorNgayMuon.setText("Định dạng ngày tháng phải là 05-03-2021");
        } else {
            jLabelErrorNgayMuon.setText("");
            check++;
        }

        if (ngayTra == null) {
            jLabelErrorNgayTra.setText("Định dạng ngày tháng phải là 05-03-2021");
        } else {
            check++;
            jLabelErrorNgayTra.setText("");
        }

        return check == 2
                ? new PhieuMuon(maPhieuMuon,
                        "nguoiMuon",
                        Helper.Auth.user.getMaQL(),
                        ngayMuon, ngayTra, "sach-" + Calendar.getInstance().getTimeInMillis())
                : null;
    }

    public boolean addSachMuon(Sach sach) {
        if (ListSachMuon.containsKey(sach.getId())) {
            return false;
        } else {
            ListSachMuon.put(sach.getId(), sach);
            tableModelSachMuon.addRow(new Object[]{sach.getId(), sach.getTenSach(), sach.getNhaXuatBan()});
            return true;
        }
    }

    public String addSachFromSacanner(String key) {
        Sach sach = null; //use key find sach

        if (sach != null) {
            tableModelSachMuon.addRow(new Object[]{sach.getId(), sach.getTenSach(), sach.getNhaXuatBan()});
            return sach.getTenSach();
        }
        return null;
    }
}
