/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.SachDAO;
import DAO.ThongKeDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Helper.MsgBox;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author NguyenHoan
 */
public final class ThongKe_JPanel extends javax.swing.JPanel {

    private ThongKeDAO thongKeDAO;
    private SachDAO sachDAO;
    private List<Object[]> listTreHan;

    private static ThongKe_JPanel instance;

    /**
     * Creates new form ThongKe_JPanel
     */
    private ThongKe_JPanel() {
        initComponents();
        this.init();
    }

    private void init() {
        this.thongKeDAO = ThongKeDAO.getInstance();
        this.sachDAO = SachDAO.getInstance();
        this.fillTableSachDaMuon();
        this.fillTableSachBiLoai();
        this.fillTableSachConLai();
        fillTableSachTreHan();
    }

    void fillTableDaMuon() {
        DefaultTableModel model = (DefaultTableModel) this.tblSachDaMuon.getModel();
        model.setRowCount(0);
        List<Object[]> list = this.thongKeDAO.getSachDaMuon();
//        list.forEach(row -> {
//            model.addRow(new Object[]{row[0],row[1],row[2],row[3],row[4],row[0],row[0]
//            });
//        });
    }

    public static ThongKe_JPanel getInstance() {
        if (instance == null) {
            instance = new ThongKe_JPanel();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDaMuon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachDaMuon = new javax.swing.JTable();
        pnlBiloai = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSachBiLoai = new javax.swing.JTable();
        pnlTreHan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSachTreHan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSendMail = new javax.swing.JButton();
        pnlConLai = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSachConLai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnlDaMuon.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setColumnHeaderView(null);

        tblSachDaMuon.setAutoCreateRowSorter(true);
        tblSachDaMuon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSachDaMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sách", "Tên sách", "Tách giả", "Thể loại", "Nhà xuất bản", "Ngày mượn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSachDaMuon.setGridColor(new java.awt.Color(255, 255, 255));
        tblSachDaMuon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSachDaMuon.setRowHeight(25);
        tblSachDaMuon.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane1.setViewportView(tblSachDaMuon);
        if (tblSachDaMuon.getColumnModel().getColumnCount() > 0) {
            tblSachDaMuon.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout pnlDaMuonLayout = new javax.swing.GroupLayout(pnlDaMuon);
        pnlDaMuon.setLayout(pnlDaMuonLayout);
        pnlDaMuonLayout.setHorizontalGroup(
            pnlDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDaMuonLayout.setVerticalGroup(
            pnlDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đã mượn", pnlDaMuon);

        pnlBiloai.setBackground(new java.awt.Color(255, 255, 255));
        pnlBiloai.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblSachBiLoai.setAutoCreateRowSorter(true);
        tblSachBiLoai.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSachBiLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sách", "Tên sách", "Tách giả", "Thể loại", "Nhà xuất bản", "Vị trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSachBiLoai.setGridColor(new java.awt.Color(255, 255, 255));
        tblSachBiLoai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSachBiLoai.setRowHeight(25);
        tblSachBiLoai.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane4.setViewportView(tblSachBiLoai);
        if (tblSachBiLoai.getColumnModel().getColumnCount() > 0) {
            tblSachBiLoai.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        pnlBiloai.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Bị loại", pnlBiloai);

        pnlTreHan.setBackground(new java.awt.Color(255, 255, 255));
        pnlTreHan.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblSachTreHan.setAutoCreateRowSorter(true);
        tblSachTreHan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSachTreHan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Người Mượn", "Email", "Số Điện Thoại", "Mã sách", "Tên sách", "Tách giả", "Thể loại", "Nhà xuất bản", "Ngày hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSachTreHan.setGridColor(new java.awt.Color(255, 255, 255));
        tblSachTreHan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSachTreHan.setRowHeight(25);
        tblSachTreHan.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane2.setViewportView(tblSachTreHan);
        if (tblSachTreHan.getColumnModel().getColumnCount() > 0) {
            tblSachTreHan.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblSachTreHan.getColumnModel().getColumn(0).setMaxWidth(100);
            tblSachTreHan.getColumnModel().getColumn(4).setMaxWidth(100);
            tblSachTreHan.getColumnModel().getColumn(7).setResizable(false);
            tblSachTreHan.getColumnModel().getColumn(9).setResizable(false);
        }

        pnlTreHan.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnSendMail.setText("Gửi mail thông báo");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSendMail)
                .addContainerGap(689, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSendMail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTreHan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Trễ hạn", pnlTreHan);

        pnlConLai.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblSachConLai.setAutoCreateRowSorter(true);
        tblSachConLai.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSachConLai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sách", "Tên sách", "Tách giả", "Thể loại", "Nhà xuất bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSachConLai.setGridColor(new java.awt.Color(255, 255, 255));
        tblSachConLai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSachConLai.setRowHeight(25);
        tblSachConLai.setSelectionBackground(new java.awt.Color(6, 143, 202));
        jScrollPane3.setViewportView(tblSachConLai);
        if (tblSachConLai.getColumnModel().getColumnCount() > 0) {
            tblSachConLai.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout pnlConLaiLayout = new javax.swing.GroupLayout(pnlConLai);
        pnlConLai.setLayout(pnlConLaiLayout);
        pnlConLaiLayout.setHorizontalGroup(
            pnlConLaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConLaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlConLaiLayout.setVerticalGroup(
            pnlConLaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConLaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Còn lại", pnlConLai);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ");
        jLabel1.setPreferredSize(new java.awt.Dimension(95, 100));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
        Long timeNow = Calendar.getInstance().getTimeInMillis();
        // date now 3/4
        //date send 3/4
        listTreHan.forEach(row -> {
            Date dateSend = ((Date) row[9]);
            if (dateSend != null && dateSend.getTime() < timeNow) {
                System.out.println(dateSend);
            }
        });
    }//GEN-LAST:event_btnSendMailActionPerformed

    void fillTableSachDaMuon() {
        DefaultTableModel model = (DefaultTableModel) this.tblSachDaMuon.getModel();
        model.setRowCount(0);
        List<Object[]> list = this.thongKeDAO.getSachDaMuon();
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{i + 1, list.get(i)[0], list.get(i)[1], list.get(i)[2], list.get(i)[3], list.get(i)[4], list.get(i)[5]});
        }
    }

    void fillTableSachBiLoai() {
        DefaultTableModel model = (DefaultTableModel) this.tblSachBiLoai.getModel();
        model.setRowCount(0);
        List<Object[]> list = this.thongKeDAO.getSachBiLoai();
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{i + 1, list.get(i)[0], list.get(i)[1], list.get(i)[2], list.get(i)[3], list.get(i)[4], list.get(i)[5]});
        }
    }

    void fillTableSachTreHan() {
        DefaultTableModel model = (DefaultTableModel) this.tblSachTreHan.getModel();
        model.setRowCount(0);
        listTreHan = this.thongKeDAO.getSachTreHan();
        System.out.println("size->" + listTreHan.size());
        for (int i = 0; i < listTreHan.size(); i++) {
            model.addRow(new Object[]{i + 1, listTreHan.get(i)[6], listTreHan.get(i)[7], listTreHan.get(i)[8], listTreHan.get(i)[0], listTreHan.get(i)[1], listTreHan.get(i)[2], listTreHan.get(i)[3], listTreHan.get(i)[4], listTreHan.get(i)[5]});
        }
    }

    void fillTableSachConLai() {
        DefaultTableModel model = (DefaultTableModel) this.tblSachConLai.getModel();
        model.setRowCount(0);
        List<Object[]> list = this.thongKeDAO.getSachConLai();
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{i + 1, list.get(i)[0], list.get(i)[1], list.get(i)[2], list.get(i)[3], list.get(i)[4], list.get(i)[5]});
        }
    }

    void thuHoi() {
        if (!Helper.Auth.isManager()) {
            MsgBox.alert_WARNING(this, "Bạn không có quyền cho thao tác này!");
            return;
        }
        for (int row : this.tblSachBiLoai.getSelectedRows()) {
            Long maSach = (Long) this.tblSachBiLoai.getValueAt(row, 2);
            this.sachDAO.delete(maSach);
        }
        MsgBox.alert_INFORMATION(this, "Thu hồi thành cống!");
    }

//    public static void main(String[] args) {
//        javax.swing.JFrame frame = new javax.swing.JFrame();
//        frame.setSize(900, 800);
//        frame.add(new ThongKe_JPanel());
//        frame.setVisible(true);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlBiloai;
    private javax.swing.JPanel pnlConLai;
    private javax.swing.JPanel pnlDaMuon;
    private javax.swing.JPanel pnlTreHan;
    private javax.swing.JTable tblSachBiLoai;
    private javax.swing.JTable tblSachConLai;
    private javax.swing.JTable tblSachDaMuon;
    private javax.swing.JTable tblSachTreHan;
    // End of variables declaration//GEN-END:variables
}
